{
 "title": "AMQ Broker",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Queue Size for 'test-queue'",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "activemq_queue_size{service=\"jboss-amq-tcp\", namespace=\"dev\", queue=\"test-queue\"}"
    }
   ]
  },
  {
   "title": "AMQ Broker Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"jboss-amq-tcp\", namespace=\"dev\"}"
    }
   ]
  },
  {
   "title": "Average Enqueue Time for 'test-queue'",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "activemq_queue_avg_enqueue_time{service=\"jboss-amq-tcp\", namespace=\"dev\", queue=\"test-queue\"}"
    }
   ]
  },
  {
   "title": "Enqueue rate for 'test-queue'",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(activemq_queue_enqueue_count{service=\"jboss-amq-tcp\", namespace=\"dev\", queue=\"test-queue\"}[1m])"
    }
   ]
  },
  {
   "title": "AMQ Broker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"jboss-amq-tcp\", namespace=\"dev\"}[5m])"
    }
   ]
  },
  {
   "title": "Dequeue rate for 'test-queue'",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(activemq_queue_dequeue_count{service=\"jboss-amq-tcp\", namespace=\"dev\", queue=\"test-queue\"}[1m])"
    }
   ]
  }
 ]
}