{
 "title": "Test Service",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Test Processor Average Processing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{processor=\"\\\"test-processor\\\"\", service=\"test-service\"}"
    }
   ]
  },
  {
   "title": "Test Service Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"test-service\", namespace=\"test-serviceservice\"}"
    }
   ]
  },
  {
   "title": "Test Processor Processing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{processor=\"\\\"test-processor\\\"\", service=\"test-service\"}"
    }
   ]
  },
  {
   "title": "Test Service Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{service=\"test-service\"}"
    }
   ]
  },
  {
   "title": "Test Route Processing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_MeanProcessingTime{route=\"\\\"test-route\\\"\", service=\"test-service\"}"
    }
   ]
  }
 ]
}