global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:25'
  smtp_from: 'prometheus@example.com'
  smtp_auth_username: 'smtp-user'
  smtp_auth_password: 'smtp-password'
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'noc@example.com'
