apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus
    role: alert-rules
  name: pod-restarting
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodRestarting
      annotations:
        message: A pod is in a restart loop.
      expr: avg without(instance)(changes(process_start_time_seconds[1h])) > 3
      for: 10m
      labels:
        severity: critical
